const languageData = {
  en: {
    language: 'Language',
    english: 'English',
    spanish: 'Spanish',
    french: 'French',
    refresh: 'Refresh',
    shortcut: 'Shortcut',
    headText: 'Notes',
    version: 'Version 1.1.0',
    trash: 'Trash',
    archive: 'Archive',
    calendar: 'Calendar',
    search: 'Search',
    addLabels: 'Add Labels',
    allNotes: 'All notes',
    settings: 'Settings',
    labelsList: 'Labels',
  },
  es: {
    language: 'Idioma',
    english: 'Inglés',
    spanish: 'Español',
    french: 'Francés',
    refresh: 'Actualizar',
    shortcut: 'Acceso directo',
    headText: 'Notas',
    version: 'Versión 1.1.0',
    trash: 'Basura',
    archive: 'Archivo',
    calendar: 'Calendario',
    search: 'Buscar',
    addLabels: 'Agregar etiquetas',
    allNotes: 'Todas las notas',
    settings: 'Configuraciones',
    labelsList: 'Etiquetas',
  },
  fr: {
    language: 'Langue',
    english: 'Anglais',
    spanish: 'Espagnol',
    french: 'Français',
    refresh: 'Rafraîchir',
    shortcut: 'Raccourci',
    headText: 'Notes',
    version: 'Version 1.1.0',
    trash: 'Poubelle',
    archive: 'Archive',
    calendar: 'Calendrier',
    search: 'Rechercher',
    addLabels: 'Ajouter des étiquettes',
    allNotes: 'Toutes les notes',
    settings: 'Paramètres',
    labelsList: 'Étiquettes',
  },
};

export default languageData;
