const languageData = {
  en: {
    // Sidebar
    language: 'Language',
    english: 'English',
    spanish: 'Spanish',
    french: 'French',
    german: 'German',
    italian: 'Italian',
    portuguese: 'Portuguese',
    russian: 'Russian',
    turkish: 'Turkish',
    azerbaijani: 'Azerbaijani',
    polish: 'Polish',
    dutch: 'Dutch',
    swedish: 'Swedish',
    norwegian: 'Norwegian',
    finnish: 'Finnish',
    refresh: 'Refresh',
    shortcut: 'Shortcut',
    headText: 'Notes',
    version: 'Version 1.1.0',
    trash: 'Trash',
    archive: 'Archive',
    calendar: 'Calendar',
    search: 'Search',
    addLabels: 'Add label',
    allNotes: 'All notes',
    settings: 'Settings',
    labelsList: 'Labels',
    category: 'Categories',
    viewCalendar: 'View calendar',
    createEvent: 'Create event',
    addCategory: 'Add category',
    myNotes: 'My notes',
    today: 'Today',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    year: 'Year',
    schedule: 'Schedule',
    sidebar: 'Sidebar',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Add note',
  },

  es: {
    // Sidebar
    language: 'Idioma',
    english: 'Inglés',
    spanish: 'Español',
    french: 'Francés',
    german: 'Alemán',
    italian: 'Italiano',
    portuguese: 'Portugués',
    russian: 'Ruso',
    turkish: 'Turco',
    azerbaijani: 'Azerbaiyano',
    polish: 'Polaco',
    dutch: 'Neerlandés',
    swedish: 'Sueco',
    norwegian: 'Noruego',
    finnish: 'Finlandés',
    refresh: 'Actualizar',
    shortcut: 'Acceso directo',
    headText: 'Notas',
    version: 'Versión 1.1.0',
    trash: 'Basura',
    archive: 'Archivo',
    calendar: 'Calendario',
    search: 'Buscar',
    addLabels: 'Agregar etiqueta',
    allNotes: 'Todas las notas',
    settings: 'Configuraciones',
    labelsList: 'Etiquetas',
    category: 'Categorías',
    viewCalendar: 'Ver calendario',
    createEvent: 'Crear evento',
    addCategory: 'Añadir categoría',
    myNotes: 'Mis notas',
    today: 'Hoy',
    day: 'Día',
    week: 'Semana',
    month: 'Mes',
    year: 'Año',
    schedule: 'Horario',
    sidebar: 'Barra lateral',

    // Sidebar => Notes => Add note section
    addNote: 'Agregar nota',
  },

  fr: {
    // Sidebar
    language: 'Langue',
    english: 'Anglais',
    spanish: 'Espagnol',
    french: 'Français',
    german: 'Allemand',
    italian: 'Italien',
    portuguese: 'Portugais',
    russian: 'Russe',
    turkish: 'Turc',
    azerbaijani: 'Azéri',
    polish: 'Polonais',
    dutch: 'Néerlandais',
    swedish: 'Suédois',
    norwegian: 'Norvégien',
    finnish: 'Finnois',
    refresh: 'Rafraîchir',
    shortcut: 'Raccourci',
    headText: 'Notes',
    version: 'Version 1.1.0',
    trash: 'Poubelle',
    archive: 'Archive',
    calendar: 'Calendrier',
    search: 'Rechercher',
    addLabels: 'Ajouter une étiquette',
    allNotes: 'Toutes les notes',
    settings: 'Paramètres',
    labelsList: 'Étiquettes',
    category: 'Catégories',
    viewCalendar: 'Voir le calendrier',
    createEvent: 'Créer un événement',
    addCategory: 'Ajouter une catégorie',
    myNotes: 'Mes notes',
    today: 'Aujourd\'hui',
    day: 'Jour',
    week: 'Semaine',
    month: 'Mois',
    year: 'Année',
    schedule: 'Emploi du temps',
    sidebar: 'Barre latérale',

    // Sidebar => Notes => Add note section
    addNote: 'Ajouter une note',
  },

  de: {
    // Sidebar
    language: 'Sprache',
    english: 'Englisch',
    spanish: 'Spanisch',
    french: 'Französisch',
    german: 'Deutsch',
  italian: 'Italienisch',
    portuguese: 'Portugiesisch',
    russian: 'Russisch',
    turkish: 'Türkisch',
    azerbaijani: 'Aserbaidschanisch',
    polish: 'Polnisch',
    dutch: 'Niederländisch',
    swedish: 'Schwedisch',
    norwegian: 'Norwegisch',
    finnish: 'Finnisch',
    refresh: 'Aktualisieren',
    shortcut: 'Verknüpfung',
    headText: 'Notizen',
    version: 'Version 1.1.0',
    trash: 'Papierkorb',
    archive: 'Archiv',
    calendar: 'Kalender',
    search: 'Suche',
    addLabels: 'Label hinzufügen',
    allNotes: 'Alle Notizen',
    settings: 'Einstellungen',
    labelsList: 'Labels',
    category: 'Kategorien',
    viewCalendar: 'Kalender anzeigen',
    createEvent: 'Ereignis erstellen',
    addCategory: 'Kategorie hinzufügen',
    myNotes: 'Meine Notizen',
    today: 'Heute',
    day: 'Tag',
    week: 'Woche',
    month: 'Monat',
    year: 'Jahr',
    schedule: 'Zeitplan',
    sidebar: 'Seitenleiste',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Notiz hinzufügen'
  },

  it: {
    // Sidebar
    language: 'Lingua',
    english: 'Inglese',
    spanish: 'Spagnolo',
    french: 'Francese',
    german: 'Tedesco',
    italian: 'Italiano',
    portuguese: 'Portoghese',
    russian: 'Russo',
    turkish: 'Turco',
    azerbaijani: 'Azerbaigiano',
    polish: 'Polacco',
    dutch: 'Olandese',
    swedish: 'Svedese',
    norwegian: 'Norvegese',
    finnish: 'Finlandese',
    refresh: 'Aggiorna',
    shortcut: 'Scorciatoia',
    headText: 'Note',
    version: 'Versione 1.1.0',
    trash: 'Cestino',
    archive: 'Archivio',
    calendar: 'Calendario',
    search: 'Cerca',
    addLabels: 'Aggiungi etichetta',
    allNotes: 'Tutte le note',
    settings: 'Impostazioni',
    labelsList: 'Etichette',
    category: 'Categorie',
    viewCalendar: 'Visualizza calendario',
    createEvent: 'Crea evento',
    addCategory: 'Aggiungi categoria',
    myNotes: 'Le mie note',
    today: 'Oggi',
    day: 'Giorno',
    week: 'Settimana',
    month: 'Mese',
    year: 'Anno',
    schedule: 'Programma',
    sidebar: 'Barra laterale',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Aggiungi nota'
  },

  pt: {
    // Sidebar
    language: 'Idioma',
    english: 'Inglês',
    spanish: 'Espanhol',
    french: 'Francês',
    portuguese: 'Português',
    german: 'Alemão',
    italian: 'Italiano',
    russian: 'Russo',
    turkish: 'Turco',
    azerbaijani: 'Azerbaijano',
    polish: 'Polaco',
    dutch: 'Holandês',
    swedish: 'Sueco',
    norwegian: 'Norueguês',
    finnish: 'Finlandês',
    refresh: 'Atualizar',
    shortcut: 'Atalho',
    headText: 'Notas',
    version: 'Versão 1.1.0',
    trash: 'Lixeira',
    archive: 'Arquivo',
    calendar: 'Calendário',
    search: 'Buscar',
    addLabels: 'Adicionar etiqueta',
    allNotes: 'Todas as notas',
    settings: 'Configurações',
    labelsList: 'Etiquetas',
    category: 'Categorias',
    viewCalendar: 'Visualizar calendário',
    createEvent: 'Criar evento',
    addCategory: 'Adicionar categoria',
    myNotes: 'Minhas notas',
    today: 'Hoje',
    day: 'Dia',
    week: 'Semana',
    month: 'Mês',
    year: 'Ano',
    schedule: 'Agenda',
    sidebar: 'Barra lateral',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Adicionar nota'
  },

  ru: {
    // Sidebar
    language: 'Язык',
    english: 'Английский',
    spanish: 'Испанский',
    french: 'Французский',
    german: 'Немецкий',
    italian: 'Итальянский',
    portuguese: 'Португальский',
    russian: 'Русский',
    turkish: 'Турецкий',
    azerbaijani: 'Азербайджанский',
    polish: 'Польский',
    dutch: 'Нидерландский',
    swedish: 'Шведский',
    norwegian: 'Норвежский',
    finnish: 'Финский',
    refresh: 'Обновить',
    shortcut: 'Ярлык',
    headText: 'Заметки',
    version: 'Версия 1.1.0',
    trash: 'Корзина',
    archive: 'Архив',
    calendar: 'Календарь',
    search: 'Поиск',
    addLabels: 'Добавить метку',
    allNotes: 'Все заметки',
    settings: 'Настройки',
    labelsList: 'Метки',
    category: 'Категории',
    viewCalendar: 'Просмотр календаря',
    createEvent: 'Создать событие',
    addCategory: 'Добавить категорию',
    myNotes: 'Мои заметки',
    today: 'Сегодня',
    day: 'День',
    week: 'Неделя',
    month: 'Месяц',
    year: 'Год',
    schedule: 'Расписание',
    sidebar: 'Боковая панель',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Добавить заметку'
  },

  tr: {
    // Sidebar
    language: 'Dil',
    english: 'İngilizce',
    spanish: 'İspanyolca',
    french: 'Fransızca',
    german: 'Almanca',
  italian: 'İtalyanca',
    portuguese: 'Portekizce',
    russian: 'Rusça',
    turkish: 'Türkçe',
    azerbaijani: 'Azerbaycan Dili',
    polish: 'Lehçe',
    dutch: 'Hollandaca',
    swedish: 'İsveççe',
    norwegian: 'Norveççe',
    finnish: 'Fince',
    refresh: 'Yenile',
    shortcut: 'Kısayol',
    headText: 'Notlar',
    version: 'Sürüm 1.1.0',
    trash: 'Çöp Kutusu',
    archive: 'Arşiv',
    calendar: 'Takvim',
    search: 'Arama',
    addLabels: 'Etiket Ekle',
    allNotes: 'Tüm Notlar',
    settings: 'Ayarlar',
    labelsList: 'Etiketler',
    category: 'Kategoriler',
    viewCalendar: 'Takvimi Görüntüle',
    createEvent: 'Etkinlik Oluştur',
    addCategory: 'Kategori Ekle',
    myNotes: 'Benim Notlarım',
    today: 'Bugün',
    day: 'Gün',
    week: 'Hafta',
    month: 'Ay',
    year: 'Yıl',
    schedule: 'Program',
    sidebar: 'Yan Menü',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Not Ekle'
  },

  az: {
    // Sidebar
    language: 'Dil',
    english: 'İngilis dili',
    spanish: 'İspan dili',
    french: 'Fransız dili',
    german: 'Alman dili',
  italian: 'İtalyan dili',
    portuguese: 'Portuqal dili',
    russian: 'Rus dili',
    turkish: 'Türk dili',
    azerbaijani: 'Azərbaycan dili',
    polish: 'Polyak dili',
    dutch: 'Hollandiya dili',
    swedish: 'İsveç dili',
    norwegian: 'Norveç dili',
    finnish: 'Fin dili',
    refresh: 'Yenilə',
    shortcut: 'Qısa yol',
    headText: 'Qeydlər',
    version: 'Versiya 1.1.0',
    trash: 'Təhlükəsizlik qutusu',
    archive: 'Arxiv',
    calendar: 'Təqvim',
    search: 'Axtarış',
    addLabels: 'Etiket əlavə et',
    allNotes: 'Bütün qeydlər',
    settings: 'Tənzimləmələr',
    labelsList: 'Etiketlər',
    category: 'Kateqoriyalar',
    viewCalendar: 'Təqvimi göstər',
    createEvent: 'Hadisə yaradın',
    addCategory: 'Kateqoriya əlavə et',
    myNotes: 'Mənim qeydlərim',
    today: 'Bugün',
    day: 'Gün',
    week: 'Həftə',
    month: 'Ay',
    year: 'İl',
    schedule: 'Cədvəl',
    sidebar: 'Yan panel',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Qeyd əlavə et'
  },

  pl: {
    // Sidebar
    language: 'Język',
    english: 'Angielski',
    spanish: 'Hiszpański',
    french: 'Francuski',
    german: 'Niemiecki',
    italian: 'Włoski',
    portuguese: 'Portugalski',
    russian: 'Rosyjski',
    turkish: 'Turecki',
    azerbaijani: 'Azerbejdżański',
    polish: 'Polski',
    dutch: 'Niderlandzki',
    swedish: 'Szwedzki',
    norwegian: 'Norweski',
    finnish: 'Fiński',
    refresh: 'Odśwież',
    shortcut: 'Skrót',
    headText: 'Notatki',
    version: 'Wersja 1.1.0',
    trash: 'Kosz',
    archive: 'Archiwum',
    calendar: 'Kalendarz',
    search: 'Szukaj',
    addLabels: 'Dodaj etykietę',
    allNotes: 'Wszystkie notatki',
    settings: 'Ustawienia',
    labelsList: 'Etykiety',
    category: 'Kategorie',
    viewCalendar: 'Pokaż kalendarz',
    createEvent: 'Utwórz wydarzenie',
    addCategory: 'Dodaj kategorię',
    myNotes: 'Moje notatki',
    today: 'Dziś',
    day: 'Dzień',
    week: 'Tydzień',
    month: 'Miesiąc',
    year: 'Rok',
    schedule: 'Harmonogram',
    sidebar: 'Pasek boczny',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Dodaj notatkę'
  },

  nl: {
    // Sidebar
    language: 'Taal',
    english: 'Engels',
    spanish: 'Spaans',
    french: 'Frans',
    german: 'Duits',
    italian: 'Italiaans',
    portuguese: 'Portugees',
    russian: 'Russisch',
    turkish: 'Turks',
    azerbaijani: 'Azerbeidzjaans',
    polish: 'Pools',
    dutch: 'Nederlands',
    swedish: 'Zweeds',
    norwegian: 'Noors',
    finnish: 'Fins',
    refresh: 'Vernieuwen',
    shortcut: 'Snelkoppeling',
    headText: 'Notities',
    version: 'Versie 1.1.0',
    trash: 'Prullenbak',
    archive: 'Archief',
    calendar: 'Kalender',
    search: 'Zoeken',
    addLabels: 'Label toevoegen',
    allNotes: 'Alle notities',
    settings: 'Instellingen',
    labelsList: 'Labels',
    category: 'Categorieën',
    viewCalendar: 'Bekijk kalender',
    createEvent: 'Evenement aanmaken',
    addCategory: 'Categorie toevoegen',
    myNotes: 'Mijn notities',
    today: 'Vandaag',
    day: 'Dag',
    week: 'Week',
    month: 'Maand',
    year: 'Jaar',
    schedule: 'Schema',
    sidebar: 'Zijbalk',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Notitie toevoegen'
  },

  sv: {
    // Sidebar
    language: 'Språk',
    english: 'Engelska',
    spanish: 'Spanska',
    french: 'Franska',
    german: 'Tyska',
  italian: 'Italienska',
    portuguese: 'Portugisiska',
    russian: 'Ryska',
    turkish: 'Turkiska',
    azerbaijani: 'Azerbajdzjanska',
    polish: 'Polska',
    dutch: 'Holländska',
    swedish: 'Svenska',
    norwegian: 'Norska',
    finnish: 'Finska',
    refresh: 'Uppdatera',
    shortcut: 'Genväg',
    headText: 'Anteckningar',
    version: 'Version 1.1.0',
    trash: 'Papperskorg',
    archive: 'Arkiv',
    calendar: 'Kalender',
    search: 'Sök',
    addLabels: 'Lägg till etikett',
    allNotes: 'Alla anteckningar',
    settings: 'Inställningar',
    labelsList: 'Etiketter',
    category: 'Kategorier',
    viewCalendar: 'Visa kalender',
    createEvent: 'Skapa evenemang',
    addCategory: 'Lägg till kategori',
    myNotes: 'Mina anteckningar',
    today: 'Idag',
    day: 'Dag',
    week: 'Vecka',
    month: 'Månad',
    year: 'År',
    schedule: 'Schema',
    sidebar: 'Sidomeny',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Lägg till anteckning'
  },

  no: {
    // Sidebar
    language: 'Språk',
    english: 'Engelsk',
    spanish: 'Spansk',
    french: 'Fransk',
    german: 'Tysk',
    italian: 'Italiensk',
    portuguese: 'Portugisisk',
    russian: 'Russisk',
    turkish: 'Tyrkisk',
    azerbaijani: 'Aserbajdsjansk',
    polish: 'Polsk',
    dutch: 'Nederlandsk',
    swedish: 'Svensk',
    norwegian: 'Norsk',
    finnish: 'Finsk',
    refresh: 'Oppdater',
    shortcut: 'Snarvei',
    headText: 'Notater',
    version: 'Versjon 1.1.0',
    trash: 'Papirkurv',
    archive: 'Arkiv',
    calendar: 'Kalendar',
    search: 'Søk',
    addLabels: 'Legg til etikett',
    allNotes: 'Alle notater',
    settings: 'Innstillinger',
    labelsList: 'Etiketter',
    category: 'Kategorier',
    viewCalendar: 'Vis kalender',
    createEvent: 'Lag hendelse',
    addCategory: 'Legg til kategori',
    myNotes: 'Mine notater',
    today: 'I dag',
    day: 'Dag',
    week: 'Uke',
    month: 'Måned',
    year: 'År',
    schedule: 'Tidsskjema',
    sidebar: 'Sidepanel',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Legg til notat'
  },

  fi: {
    // Sidebar
    language: 'Kieli',
    english: 'Englanti',
    spanish: 'Espanja',
    french: 'Ranska',
    german: 'Saksa',
    italian: 'Italia',
    portuguese: 'Portugali',
    russian: 'Venäjä',
    turkish: 'Turkki',
    azerbaijani: 'Azerbaidžani',
    polish: 'Puola',
    dutch: 'Hollanti',
    swedish: 'Ruotsi',
    norwegian: 'Norja',
    finnish: 'Suomi',
    refresh: 'Päivitä',
    shortcut: 'Pikanäppäin',
    headText: 'Muistiinpanot',
    version: 'Versio 1.1.0',
    trash: 'Roskakori',
    archive: 'Arkisto',
    calendar: 'Kalenteri',
    search: 'Haku',
    addLabels: 'Lisää etiketti',
    allNotes: 'Kaikki muistiinpanot',
    settings: 'Asetukset',
    labelsList: 'Etiketit',
    category: 'Kategoriat',
    viewCalendar: 'Näytä kalenteri',
    createEvent: 'Luo tapahtuma',
    addCategory: 'Lisää kategoria',
    myNotes: 'Omat muistiinpanot',
    today: 'Tänään',
    day: 'Päivä',
    week: 'Viikko',
    month: 'Kuukausi',
    year: 'Vuosi',
    schedule: 'Aikataulu',
    sidebar: 'Sivupaneeli',

    // Sidebar => Calendar/Notes => Shortcuts

    // Sidebar => Notes => Add note section
    addNote: 'Lisää muistiinpano'
  },















};

export default languageData;
