const languageData = {
  en: {
    // Sidebar
    language: 'Language',
    english: 'English',
    spanish: 'Spanish',
    french: 'French',
    refresh: 'Refresh',
    shortcut: 'Shortcut',
    headText: 'Notes',
    version: 'Version 1.1.0',
    trash: 'Trash',
    archive: 'Archive',
    calendar: 'Calendar',
    search: 'Search',
    addLabels: 'Add label',
    allNotes: 'All notes',
    settings: 'Settings',
    labelsList: 'Labels',
    category: 'Categories',
    viewCalendar: 'View calendar',
    createEvent: 'Create event',
    addCategory: 'Add category',
    myNotes: 'My notes',
    today: 'Today',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    year: 'Year',
    schedule: 'Schedule',
    
    // Sidebar => Calendar/Notes => Shortcuts
  },
  es: {
    language: 'Idioma',
    english: 'Inglés',
    spanish: 'Español',
    french: 'Francés',
    refresh: 'Actualizar',
    shortcut: 'Acceso directo',
    headText: 'Notas',
    version: 'Versión 1.1.0',
    trash: 'Basura',
    archive: 'Archivo',
    calendar: 'Calendario',
    search: 'Buscar',
    addLabels: 'Agregar etiqueta',
    allNotes: 'Todas las notas',
    settings: 'Configuraciones',
    labelsList: 'Etiquetas',
    category: 'Categorías',
    viewCalendar: 'Ver calendario',
    createEvent: 'Crear evento',
    addCategory: 'Añadir categoría',
    myNotes: 'Mis notas',
    today: 'Hoy',
    day: 'Día',
    week: 'Semana',
    month: 'Mes',
    year: 'Año',
    schedule: 'Horario',
  },
  fr: {
    language: 'Langue',
    english: 'Anglais',
    spanish: 'Espagnol',
    french: 'Français',
    refresh: 'Rafraîchir',
    shortcut: 'Raccourci',
    headText: 'Notes',
    version: 'Version 1.1.0',
    trash: 'Poubelle',
    archive: 'Archive',
    calendar: 'Calendrier',
    search: 'Rechercher',
    addLabels: 'Ajouter une étiquette',
    allNotes: 'Toutes les notes',
    settings: 'Paramètres',
    labelsList: 'Étiquettes',
    category: 'Catégories',
    viewCalendar: 'Voir le calendrier',
    createEvent: 'Créer un événement',
    addCategory: 'Ajouter une catégorie',
    myNotes: 'Mes notes',
    today: 'Aujourd\'hui',
    day: 'Jour',
    week: 'Semaine',
    month: 'Mois',
    year: 'Année',
    schedule: 'Emploi du temps',
  },
};

export default languageData;
